##
# Docker image for deploying the Lurch Slack bot.
#
# This provides an image suitable for deployment in a production environment.
# This image is automatically generated by Drone CI (see .drone.yml for
# details).
#

FROM scratch
MAINTAINER Homme Zwaagstra <hrz@geodata.soton.ac.uk>

# Install the SSL/TLS root certificates.
ADD cacert.pem /etc/ssl/certs/ca-certificates.crt

# Install the lurch binary.
ADD ./lurch /bin/

ENTRYPOINT ["/bin/lurch"]
